# Generated by Django 2.2.6 on 2019-10-06 17:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_signup', '0002_auto_20190928_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='firstnames',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='lastnames',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
    ]
